### ISSUE TITLE
could you give me a demo how to use this ipdb-packer? please...

### ISSUE THREAD

**Issue by vampire007** [metowolf/ipdb-packer#1]
could you give me a demo how to use this ipdb-packer? please...  thanks~~

**Comment by metowolf** [comment]
https://github.com/metowolf/qqwry.ipdb/blob/master/src/packer_raw.js

**Comment by billsteve** [comment]
when i run "node .\packer_raw.js",i got this：
no such file or directory, open './build/qqwry.dat'
